### ISSUE TITLE
Pause button does not work :(

### ISSUE THREAD

**Issue by cd1etrich** [tim-we/py-radio#27]
Tim, please fix. I want to pause my meme songs to play meme songs that are not on the py, but on my phone, but instead it just skips =( TIM FIX OR I WANT A REFUND
Sincerely,
Josh from Microsoft Tech Support

**Comment by tim-we** [comment]
My good Sir, I'd like you to inform you that it's pi - not py.

**Comment by cd1etrich** [comment]
Just gimme a moment, please...
Yes, I'm calling from London today.

Please install TeamViewer app. This is the only way to fix this issue 

Good day to you sir!

**Comment by cd1etrich** [comment]
Yes sir. To help you please visit razzpberripie.techsupport.net ! Then install TeamViewer app.
